layout_spectrum: 0.4190221047028899
typography_spectrum: 0.9845003287773579
color:
  brandStrength: 0.5974522144533694
  lightness: 0.16141845285892487
  saturation: 0.3410785784944892
  rhythmicContrast: 0.43649836140684783
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Nico
